# Generated by Django 2.2.5 on 2019-09-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.IntegerField()),
                ('source', models.CharField(max_length=11, null=True)),
                ('destination', models.CharField(max_length=11, null=True)),
                ('duration', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('reference_period', models.CharField(max_length=7, null=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
